"""Feature 4: Application Copilot.

Generates an application checklist, a first-draft SOP, cover letter, and a
cold email to a matched professor. SOP/email/cover letter use WRITING_MODEL
with the prompts in app/prompts/, which forbid inventing achievements. In demo
mode (or if the API call fails) honest templates built only from profile facts
are used, with [bracketed] gaps for the student to fill in.

Every draft opens with an "AI draft — edit before sending" label.
"""
from datetime import date

from app.models.opportunity import Opportunity
from app.models.profile import Profile
from app.models.user import User
from app.services.fields import norm
from app.services.llm import LLMUnavailable, complete_text, llm_enabled, load_prompt

AI_LABEL = "> **AI draft — edit before sending.** Generated by ScholarRadar from your profile; check every line."

DEGREE_WORDS = {"bachelors": "undergraduate", "masters": "Master's", "phd": "PhD"}
TECH_FIELDS = {"ai/ml", "computer science", "data science", "engineering"}


def _ordinal(n: int | None) -> str:
    if not n:
        return ""
    return f"{n}{'th' if 11 <= n % 100 <= 13 else {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')}"


def _student_line(user: User, p: Profile | None) -> str:
    if not p or not p.degree_level:
        return "a student"
    year = f"{_ordinal(p.year_of_study)}-year " if p.year_of_study else ""
    major = f" {p.major}" if p.major else ""
    return f"a {year}{DEGREE_WORDS.get(p.degree_level, p.degree_level)}{major} student"


def profile_facts(user: User, p: Profile | None, include_cv: bool = True) -> str:
    lines = [f"Name: {user.name}"]
    if p:
        if p.degree_level:
            lines.append(f"Degree level: {p.degree_level}")
        if p.year_of_study:
            lines.append(f"Year of study: {p.year_of_study}")
        if p.major:
            lines.append(f"Major: {p.major}")
        if p.cgpa is not None:
            lines.append(f"CGPA: {p.cgpa}/{p.cgpa_scale:g}")
        if p.english_tests:
            lines.append("English tests: " + ", ".join(f"{k} {v:g}" for k, v in p.english_tests.items()))
        if p.skills:
            lines.append("Skills: " + ", ".join(p.skills))
        if p.interests:
            lines.append("Research interests: " + ", ".join(p.interests))
        if p.country_of_residence:
            lines.append(f"Lives in: {p.country_of_residence}")
        if include_cv and p.cv_text:
            lines.append("\nCV text (verbatim):\n" + p.cv_text[:8000])
    return "\n".join(lines)


def opportunity_facts(opp: Opportunity | None) -> str:
    if not opp:
        return "No specific opportunity: this is a general enquiry about research opportunities."
    lines = [f"Title: {opp.title}", f"Organization: {opp.organization}", f"Type: {opp.type.replace('_', ' ')}"]
    if opp.fields:
        lines.append("Fields: " + ", ".join(opp.fields))
    if opp.location:
        lines.append(f"Location: {opp.location}")
    if opp.deadline:
        lines.append(f"Deadline: {opp.deadline.isoformat()}")
    if opp.description_summary:
        lines.append(f"Listing text: {opp.description_summary}")
    other = (opp.eligibility or {}).get("other_requirements") or []
    if other:
        lines.append("Other requirements: " + "; ".join(other))
    return "\n".join(lines)


def _professor_facts(prof: dict | None) -> str:
    if not prof:
        return "No specific professor chosen."
    paper = prof.get("paper_title") or "[one of their recent papers]"
    year = f" ({prof['paper_year']})" if prof.get("paper_year") else ""
    return f"Professor: {prof.get('name')}\nAffiliation: {prof.get('affiliation') or 'unknown'}\nPaper to reference: {paper}{year}"


def _with_label(body: str) -> str:
    return f"{AI_LABEL}\n\n{body.strip()}\n"


# ---------- checklist (deterministic) ----------

def build_checklist(opp: Opportunity | None, p: Profile | None) -> str:
    elig = (opp.eligibility if opp else None) or {}
    fields = {norm(f) for f in ((opp.fields if opp else None) or [])}
    title = opp.title if opp else "your application"
    items = [
        "Updated CV (1-2 pages, research experience and projects first)",
        f"Statement of Purpose tailored to {opp.organization}" if opp else "Statement of Purpose",
        "Official transcripts (request early; registrars can take a week)",
        "Two letters of recommendation (ask referees at least 3 weeks ahead)",
    ]
    english = {k: v for k, v in (elig.get("english_requirements") or {}).items() if v}
    if english:
        mine = (p.english_tests if p else None) or {}
        req = " or ".join(f"{k} {v:g}" for k, v in english.items())
        have = ", ".join(f"{k} {v:g}" for k, v in mine.items()) if mine else "none on your profile yet"
        items.append(f"English test score report: {req} required (you have: {have})")
    if fields & TECH_FIELDS:
        items.append("Portfolio: GitHub, project write-ups or a short research summary")
    if opp and opp.location and not any(h in (opp.location or "").lower() for h in ("uae", "dubai", "abu dhabi", "sharjah")):
        items.append("Passport valid 6+ months beyond the programme dates (visa may be needed)")
    for extra in elig.get("other_requirements") or []:
        items.append(extra[0].upper() + extra[1:])
    if opp and opp.deadline:
        days = (opp.deadline - date.today()).days
        items.append(f"Submit before {opp.deadline.strftime('%d %b %Y')} ({days} days left). Export the deadline to your calendar")
    else:
        items.append("Confirm the deadline on the official page")
    body = f"# Application checklist: {title}\n\n" + "\n".join(f"- [ ] {i}" for i in items)
    return _with_label(body)


# ---------- templates (demo mode / fallback) ----------

def _sop_template(user: User, p: Profile | None, opp: Opportunity | None) -> str:
    interests = ", ".join((p.interests or [])[:3]) if p else ""
    skills = ", ".join((p.skills or [])[:5]) if p else ""
    org = opp.organization if opp else "[organization]"
    prog = opp.title if opp else "[programme]"
    fields = ", ".join((opp.fields or [])[:2]) if opp else "[field]"
    return f"""# Statement of Purpose

I am {_student_line(user, p)}, and I am applying to the {prog} at {org} because I want to {f"deepen my research in {interests}" if interests else "[what you want to research and why]"}. [Open with the specific question or problem that first pulled you towards this area: one concrete moment, not a general passion statement.]

My preparation so far has centred on {skills or "[your strongest technical skills]"}. [Describe your most relevant project: what you built or investigated, your specific role, and what you found. Numbers help: dataset size, accuracy, users, time saved.] [If you have a second project, describe what it taught you that the first didn't.]

What draws me to {org} specifically is its work in {fields}. [Name one or two labs, faculty members or projects listed on the official page and say how your interests connect to them. Check the page; don't guess names.]

During the programme I hope to [state 1-2 concrete goals: a skill to learn, a research question to explore, a method to apply]. In the longer term, I plan to [graduate study / research career / industry R&D], and this experience would [explain the link in one sentence].

[Close with one sentence on what you would bring to the group: persistence, a particular skill, a perspective from your background.]
"""


def _email_template(user: User, p: Profile | None, opp: Opportunity | None, prof: dict | None) -> str:
    prof_name = (prof or {}).get("name") or "[Professor's name]"
    last = prof_name.replace("Dr. ", "").split(" (")[0].split()[-1] if prof else "[Surname]"
    paper = (prof or {}).get("paper_title") or "[title of one of their recent papers]"
    interests = " and ".join((p.interests or [])[:2]) if p and p.interests else "[your research interest]"
    target = f"the {opp.title}" if opp else "a summer research project"
    return f"""**Subject:** Prospective student interested in {interests} ({target})

Dear Professor {last},

I'm {user.name}, {_student_line(user, p)}. I read your paper "{paper}", and [one sentence on the specific idea or result that connects to your own interests in {interests}].

[One line on your most relevant project or skill, with a concrete detail.]

Would you have room for a student {"through " + target if opp else "on " + target}? I'd be grateful for a short call, and I've attached my CV.

Thank you for your time,
{user.name}
"""


def _cover_letter_template(user: User, p: Profile | None, opp: Opportunity | None) -> str:
    org = opp.organization if opp else "[organization]"
    prog = opp.title if opp else "[programme]"
    skills = ", ".join((p.skills or [])[:4]) if p else "[skills]"
    return f"""# Cover Letter

Dear Selection Committee,

I am writing to apply for the {prog}. As {_student_line(user, p)}, I have built experience in {skills}, and I am keen to apply it to research at {org}.

[Describe your most relevant project or experience and what you contributed. Be specific.]

[Explain why this opportunity, at this organization, fits your goals. Reference something concrete from the official listing.]

Thank you for considering my application. I would welcome the chance to discuss it further.

Sincerely,
{user.name}
"""


# ---------- public API ----------

def _llm_draft(prompt_file: str, user: User, p: Profile | None, opp: Opportunity | None, prof: dict | None = None) -> str:
    sections = [
        "<student_profile>\n" + profile_facts(user, p) + "\n</student_profile>",
        "<opportunity>\n" + opportunity_facts(opp) + "\n</opportunity>",
    ]
    if prof is not None:
        sections.append("<professor>\n" + _professor_facts(prof) + "\n</professor>")
    sections.append("Write the draft now.")
    return complete_text(load_prompt(prompt_file), "\n\n".join(sections))


def generate(doc_type: str, user: User, profile: Profile | None, opp: Opportunity | None,
             professor: dict | None = None) -> tuple[str, str]:
    """Returns (markdown content, method) where method is "llm" or "template"."""
    if doc_type == "checklist":
        return build_checklist(opp, profile), "template"
    if doc_type == "notes":
        title = opp.title if opp else "Research notes"
        return _with_label(f"# Notes: {title}\n\n## Questions to ask\n- \n\n## Links\n- {opp.url if opp and opp.url else ''}\n"), "template"

    prompt_file, template = {
        "sop": ("sop.md", lambda: _sop_template(user, profile, opp)),
        "cold_email": ("cold_email.md", lambda: _email_template(user, profile, opp, professor)),
        "cover_letter": ("cover_letter.md", lambda: _cover_letter_template(user, profile, opp)),
    }[doc_type]
    if llm_enabled():
        try:
            # Cold emails always get a <professor> section (it says so when none was chosen).
            prof = (professor or {}) if doc_type == "cold_email" else None
            return _with_label(_llm_draft(prompt_file, user, profile, opp, prof)), "llm"
        except LLMUnavailable:
            pass
    return _with_label(template()), "template"
