"""phases 5-7 notifications outcomes cache endorsements

Revision ID: 0107c6680fc6
Revises: 29f8cf6b36a2
Create Date: 2026-10-01 21:18:13.570043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0107c6680fc6'
down_revision: Union[str, Sequence[str], None] = '29f8cf6b36a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('namespace', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_cache_key'), ['key'], unique=True)

    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('endorsements',
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('target_degree_level', sa.String(length=20), nullable=True),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('target_major', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endorsements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endorsements_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('outcomes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('share_anonymously', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_link_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_expires_at', sa.DateTime(), nullable=True))
        # server_default so existing users get {} instead of failing the NOT NULL constraint.
        batch_op.add_column(sa.Column('notification_prefs', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('last_digest_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_telegram_link_code'), ['telegram_link_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_link_code'))
        batch_op.drop_column('last_digest_at')
        batch_op.drop_column('notification_prefs')
        batch_op.drop_column('telegram_link_expires_at')
        batch_op.drop_column('telegram_link_code')

    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_user_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('endorsements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endorsements_opportunity_id'))

    op.drop_table('endorsements')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cache_key'))

    op.drop_table('api_cache')
    # ### end Alembic commands ###
